sonar.projectKey=zalduaxa-net
sonar.projectName=Zalduaxa.net
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/src,.github/workflows
sonar.tests=backend/src/test/java

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=frontend/**,.github/**
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,storage/**,**/*.class,backend/backend/**