global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "zalduaxa-backend"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "backend:8080"
        labels:
          application: "zalduaxa-net"
          service: "backend"
          environment: "local"

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "loki:3100"
        labels:
          application: "zalduaxa-net"
          service: "loki"
          environment: "local"

  - job_name: "alloy"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "alloy:12345"
        labels:
          application: "zalduaxa-net"
          service: "alloy"
          environment: "local"

  - job_name: "uptime-kuma"
    scrape_interval: 30s
    metrics_path: "/metrics"
    scheme: http
    basic_auth:
      password_file: "/etc/prometheus/secrets/uptime_kuma_api_key"
    static_configs:
      - targets:
          - "uptime-kuma:3001"
        labels:
          application: "zalduaxa-net"
          service: "uptime-kuma"
          environment: "local"

  - job_name: "matomo-analytics"
    scrape_interval: 60s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "matomo-exporter:9101"
        labels:
          application: "zalduaxa-net"
          service: "matomo-analytics"
          environment: "local"