spring.application.name=backend

# PostgreSQL datasource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/zalduaxa_net_dev}
spring.datasource.username=${DB_USERNAME:app}
spring.datasource.password=${DB_PASSWORD:app}
spring.datasource.driver-class-name=org.postgresql.Driver

# CORS
app.cors.origin=${APP_CORS_ORIGIN:http://localhost:5173}

# JWT
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}

# Backend storage path
storage.path=${STORAGE_PATH:file:/app/storage/}

# Backend default users creation
app.seed.enabled=${APP_SEED_ENABLED:false}
app.seed.admin.username=${APP_SEED_ADMIN_USERNAME:admin}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:}
app.seed.admin.email=${APP_SEED_ADMIN_EMAIL:admin@example.com}
app.seed.guest.username=${APP_SEED_GUEST_USERNAME:guest}
app.seed.guest.password=${APP_SEED_GUEST_PASSWORD:}
app.seed.guest.email=${APP_SEED_GUEST_EMAIL:guest@example.com}

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.EJB3NamingStrategy
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.default_schema=zalduaxanet